name: premium_filter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_messaging: ^15.0.4
  url_strategy: ^0.3.0
  flutter_local_notifications: ^17.1.2
  http: ^1.2.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  retry: ^3.1.2
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  xml: ^6.5.0
  pf_service:
    git:
      url: https://github.com/Marthianfred/premium_filter_service.git
      ref: master
  fluttertoast: ^8.2.5
  overlay_loading_progress: ^1.0.1
  mobile_scanner: ^5.1.1
  flutter_cached_pdfview: ^0.4.2
  dio: ^5.4.3+1


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/image/logo.png"
  image_path_android: "assets/image/logo.png"
  adaptive_icon_background: "assets/image/logo.png"
  adaptive_icon_foreground: "assets/image/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/